services:
  - type: web
    name: twitter-bot-backend
    env: python
    buildCommand: "cd server && pip install -r requirements.txt"
    startCommand: "cd server && gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0